version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: npm run start:dev
    container_name: quickdeal-bff
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app
    ports:
      - "3000:3000"
      - "9229:9229"
    depends_on:
      - db

  db:
    image: postgres
    container_name: quickdeal-postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: devdbqd
    ports:
      - "5432:5432"
    networks:
      - quickdeal-network
  
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    container_name: quickdeal-pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=pgadmin4
    ports:
      - '5050:80'
    depends_on:
      - db

volumes:
  postgres_data:

networks:
  quickdeal-network:
    driver: bridge
