
app:
  name: quickdeal-bff
  port: 3000
  port_int: 3001
  path: quickdeal_bff
  timeout: 40000
  env: deb
  log: true

security:
  jwtsecret: 'secret dev decode this in quick deal'

db:
  postgres:
    host: '127.0.0.1'
    username: 'postgres'
    password: 'postgres'
    database: 'devdbqd'
    schema: 'app'
    synchronize: true
    port: 5433
    poolMax: 2
    poolMin: 1
