
app:
  name: quickdeal-bff
  port: 3000
  port_int: 3001
  path: quickdeal_dev
  timeout: 40000
  env: dev
  log: true

db:
  postgres:
    host: 'localhost'
    username: 'postgres'
    password: 'postgres'
    database: 'devdbqd'
    schema: 'app'
    synchronize: true
    port: 5432
    poolMax: 2
    poolMin: 1
